export const trains = [
  { image: './img/trains/loco1.png' },
  { image: './img/trains/loco2.png' },
  { image: './img/trains/loco3.png' },
  { image: './img/trains/loco4.png' },
  { image: './img/trains/loco5.png' },
  { image: './img/trains/loco6.png' },
  { image: './img/trains/loco7.png' },
  { image: './img/trains/loco8.png' },
  { image: './img/trains/loco9.png' },
  { image: './img/trains/wagon1.png' },
  { image: './img/trains/wagon2.png' },
  { image: './img/trains/wagon3.png' },
  { image: './img/trains/wagon4.png' },
  { image: './img/trains/wagon5.png' },
  { image: './img/trains/wagon6.png' },
  { image: './img/trains/wagon7.png' },
  { image: './img/trains/wagon8.png' },
  { image: './img/trains/wagon9.png' },
  { image: './img/trains/wagon10.png' },
  { image: './img/trains/wagon11.png' },
  { image: './img/trains/wagon12.png' },
  { image: './img/trains/wagon13.png' },
  { image: './img/trains/wagon14.png' },
]
